### PR TITLE
Async subscription

### PR DESCRIPTION
**Pull request by dbcfd**
Builds on the work in #41 to provide an async interface for subscriptions.

### CODE REVIEW

**Comment by YoEight** [comment]
Thanks for the PR! Now I merged the ES 6 branch, I think it would be better to return an `impl Stream<Item=Result<ResolvedEvent, OperationError>>` when asking for a subscription. `PersistentSubscription` should return a tuple of a reading part (similar to the stream type above) and a writing part where you can ack/nack events.

See that link as a reference: https://github.com/YoEight/eventstore-rs/blob/master/src/es6/commands.rs#L1462

**Comment by dbcfd** [comment]
@YoEight so looking at the new master, I don't think this is needed anymore. I'm not seeing where a Subscription is returned and thus a ConsumerSubscription is needed.

Seems like ConsumerSubscription related code should just be removed.

**Comment by dbcfd** [comment]
Nm, just realized that ES6 doesn't have the consumer subscription stuff.

**Comment by dbcfd** [comment]
Yeah, I agree that the ES5 stuff should return an interface similar to ES6. Will update this PR to do that.

**Comment by YoEight** [comment]
Addressed here https://github.com/YoEight/eventstore-rs/pull/44

**Pull request closed without merging**
