### PR TITLE
Fix event id byte order

### PR DESCRIPTION
**Pull request by larsschumacher**

### CODE REVIEW

**Comment by YoEight** [comment]
Thank you very much for that patch! Could you add a `mod uuid` in `types.rs` when you add a test based on your example here https://github.com/YoEight/eventstore-rs/issues/43? I'll merge right away. I'm also planning a release later today too.

**Comment by larsschumacher** [comment]
I named the module `guid` to avoid name conflicts.

**Comment by YoEight** [comment]
Merged here https://github.com/YoEight/eventstore-rs/commit/fbcec37c3a4cd5f04a59001b3f66e916c1da14dd

**Comment by YoEight** [comment]
Thank you!

**Pull request closed without merging**
