### PR TITLE
Add logging of connection info in fmt::Debug for Connection

### PR DESCRIPTION
**Pull request by wingertge**
This change adds the size of the DiscoveryProcess enum to the Connection and requires one clone when the Connection is first created, but since Connection is usually only started and kept once per application that should be fine. I couldn't test it because the integration tests keep timing out both on the original and my modified version, probably due to the weird network issues I've been experiencing all day. The changes are minimal though so it should work fine.

### CODE REVIEW

**Comment by YoEight** [comment]
Thanks for the patch. I'm afraid your solution won't last very long considering that EventStore is moving to gRPC as its main protocol (The PR is on its way). In the meantime, we can provide a more compact way to indicate if we are dealing with single_node (and provide an IP) or a cluster. Could you share a current usage  `Connection`'s Debug formatter in your app?

**Comment by wingertge** [comment]
It would be logged automatically with a macro on my repository methods, the traces get sent to a central tracing service (Jaeger right now) so I can analyse issues.

The app will be distributed, so let's say I get queries failing in my system. I want to be able to look at the trace and see which database server I was connected to, in order to diagnose potential issues with that instance.

Here's a code example in case it's useful. I'm currently skipping the connection argument, but it contains useful tracing info that I'd rather not discard.

[connection.rs](https://github.com/wingertge/liquidity-backend-rust/blob/master/liquidity/src/db/connection.rs)

**Comment by YoEight** [comment]
Sorry, the gRPC branch absorbed me so much that I forgot about that PR. I do believe you PR would have more sense in the new gRPC client. Would you consider using your patch locally in the meantime, and let me propose you something for ES 6?

**Comment by wingertge** [comment]
Sure thing, I'm not very close to deploying publicly anyways so the tracing is just so I don't need to overhaul my whole code later. Take your time.

**Pull request closed without merging**
